# .github/workflows/release.yml
# https://github.com/rust-build/rust-build.action#build-windows-and-linux-and-upload-as-zip

on:
  release:
    types: [created]
jobs:
  release:
    name: ${{ matrix.src_dir }} (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            src_dir: client
          - target: x86_64-unknown-linux-musl
            src_dir: client
          - target: x86_64-pc-windows-gnu
            src_dir: server
          - target: x86_64-unknown-linux-musl
            src_dir: server
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: ${{ matrix.src_dir }}
