# .github/workflows/release.yml
# https://github.com/rust-build/rust-build.action#build-windows-and-linux-and-upload-as-zip

on:
  release:
    types: [created]
jobs:
  release:
    name: Build (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows
          - target: x86_64-unknown-linux-musl
            os: linux
          - target: x86_64-apple-darwin
            os: macos
          - target: aarch64-apple-darwin
            os: macos
          - target: aarch64-linux-android
            os: android
          - target: aarch64-unknown-linux-gnu
            os: raspi
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Install Windows toolchain
        if: matrix.os == 'windows'
        run: |
          rustup target add x86_64-pc-windows-msvc
      - name: Install MacOS toolchain
        if: matrix.os == 'macos'
        run: |
          rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - name: Install Linux toolchain
        if: matrix.os == 'linux'
        run: |
          sudo apt update
          sudo apt install -y musl-tools
          rustup target add x86_64-unknown-linux-musl
      - name: Install Android toolchain
        if: matrix.os == 'android'
        run: |
          rustup target add aarch64-linux-android
      - name: Install Raspi toolchain
        if: matrix.os == 'raspi'
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/garadama-client${{ matrix.os == 'windows' && '.exe' || '' }}
            target/${{ matrix.target }}/release/cicada-server${{ matrix.os == 'windows' && '.exe' || '' }}
          if-no-files-found: error
          overwrite: true

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Rename artifacts
        run: |
          cd artifacts
          for target_dir in *; do
            if [ -d "$target_dir" ]; then
              cd "$target_dir"
              for file in *; do
                project=$(echo "$file" | cut -d'-' -f1)
                component=$(echo "$file" | cut -d'-' -f2 | cut -d'.' -f1)
                extension=$([[ "$file" == *.exe ]] && echo ".exe" || echo "")
                new_name="../${project}-${{ steps.release_name.outputs.RELEASE_NAME }}-${target_dir}-${component}${extension}"
                mv "$file" "$new_name"
              done
              cd ..
              rmdir "$target_dir"
            fi
          done
      - name: Generate release name
        id: release_name
        run: echo "RELEASE_NAME=chilsonite-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.release_name.outputs.RELEASE_NAME }}
          files: |
            artifacts/**/*
          generate_release_notes: true
